# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/markus/Programming/foom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/markus/Programming/foom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markus/Programming/foom/CMakeFiles /home/markus/Programming/foom/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markus/Programming/foom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named foom

# Build rule for target.
foom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 foom
.PHONY : foom

# fast build rule for target.
foom/fast:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/build
.PHONY : foom/fast

code/Application.o: code/Application.cpp.o

.PHONY : code/Application.o

# target to build an object file
code/Application.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Application.cpp.o
.PHONY : code/Application.cpp.o

code/Application.i: code/Application.cpp.i

.PHONY : code/Application.i

# target to preprocess a source file
code/Application.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Application.cpp.i
.PHONY : code/Application.cpp.i

code/Application.s: code/Application.cpp.s

.PHONY : code/Application.s

# target to generate assembly for a file
code/Application.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Application.cpp.s
.PHONY : code/Application.cpp.s

code/Display.o: code/Display.cpp.o

.PHONY : code/Display.o

# target to build an object file
code/Display.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Display.cpp.o
.PHONY : code/Display.cpp.o

code/Display.i: code/Display.cpp.i

.PHONY : code/Display.i

# target to preprocess a source file
code/Display.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Display.cpp.i
.PHONY : code/Display.cpp.i

code/Display.s: code/Display.cpp.s

.PHONY : code/Display.s

# target to generate assembly for a file
code/Display.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Display.cpp.s
.PHONY : code/Display.cpp.s

code/Entities/Camera.o: code/Entities/Camera.cpp.o

.PHONY : code/Entities/Camera.o

# target to build an object file
code/Entities/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Entities/Camera.cpp.o
.PHONY : code/Entities/Camera.cpp.o

code/Entities/Camera.i: code/Entities/Camera.cpp.i

.PHONY : code/Entities/Camera.i

# target to preprocess a source file
code/Entities/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Entities/Camera.cpp.i
.PHONY : code/Entities/Camera.cpp.i

code/Entities/Camera.s: code/Entities/Camera.cpp.s

.PHONY : code/Entities/Camera.s

# target to generate assembly for a file
code/Entities/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Entities/Camera.cpp.s
.PHONY : code/Entities/Camera.cpp.s

code/Graphics/FrameBuffers/Bitmap.o: code/Graphics/FrameBuffers/Bitmap.cpp.o

.PHONY : code/Graphics/FrameBuffers/Bitmap.o

# target to build an object file
code/Graphics/FrameBuffers/Bitmap.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/FrameBuffers/Bitmap.cpp.o
.PHONY : code/Graphics/FrameBuffers/Bitmap.cpp.o

code/Graphics/FrameBuffers/Bitmap.i: code/Graphics/FrameBuffers/Bitmap.cpp.i

.PHONY : code/Graphics/FrameBuffers/Bitmap.i

# target to preprocess a source file
code/Graphics/FrameBuffers/Bitmap.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/FrameBuffers/Bitmap.cpp.i
.PHONY : code/Graphics/FrameBuffers/Bitmap.cpp.i

code/Graphics/FrameBuffers/Bitmap.s: code/Graphics/FrameBuffers/Bitmap.cpp.s

.PHONY : code/Graphics/FrameBuffers/Bitmap.s

# target to generate assembly for a file
code/Graphics/FrameBuffers/Bitmap.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/FrameBuffers/Bitmap.cpp.s
.PHONY : code/Graphics/FrameBuffers/Bitmap.cpp.s

code/Graphics/FrameBuffers/GameRenderer.o: code/Graphics/FrameBuffers/GameRenderer.cpp.o

.PHONY : code/Graphics/FrameBuffers/GameRenderer.o

# target to build an object file
code/Graphics/FrameBuffers/GameRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/FrameBuffers/GameRenderer.cpp.o
.PHONY : code/Graphics/FrameBuffers/GameRenderer.cpp.o

code/Graphics/FrameBuffers/GameRenderer.i: code/Graphics/FrameBuffers/GameRenderer.cpp.i

.PHONY : code/Graphics/FrameBuffers/GameRenderer.i

# target to preprocess a source file
code/Graphics/FrameBuffers/GameRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/FrameBuffers/GameRenderer.cpp.i
.PHONY : code/Graphics/FrameBuffers/GameRenderer.cpp.i

code/Graphics/FrameBuffers/GameRenderer.s: code/Graphics/FrameBuffers/GameRenderer.cpp.s

.PHONY : code/Graphics/FrameBuffers/GameRenderer.s

# target to generate assembly for a file
code/Graphics/FrameBuffers/GameRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/FrameBuffers/GameRenderer.cpp.s
.PHONY : code/Graphics/FrameBuffers/GameRenderer.cpp.s

code/Graphics/FrameBuffers/RenderContext.o: code/Graphics/FrameBuffers/RenderContext.cpp.o

.PHONY : code/Graphics/FrameBuffers/RenderContext.o

# target to build an object file
code/Graphics/FrameBuffers/RenderContext.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/FrameBuffers/RenderContext.cpp.o
.PHONY : code/Graphics/FrameBuffers/RenderContext.cpp.o

code/Graphics/FrameBuffers/RenderContext.i: code/Graphics/FrameBuffers/RenderContext.cpp.i

.PHONY : code/Graphics/FrameBuffers/RenderContext.i

# target to preprocess a source file
code/Graphics/FrameBuffers/RenderContext.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/FrameBuffers/RenderContext.cpp.i
.PHONY : code/Graphics/FrameBuffers/RenderContext.cpp.i

code/Graphics/FrameBuffers/RenderContext.s: code/Graphics/FrameBuffers/RenderContext.cpp.s

.PHONY : code/Graphics/FrameBuffers/RenderContext.s

# target to generate assembly for a file
code/Graphics/FrameBuffers/RenderContext.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/FrameBuffers/RenderContext.cpp.s
.PHONY : code/Graphics/FrameBuffers/RenderContext.cpp.s

code/Graphics/ScanLine.o: code/Graphics/ScanLine.cpp.o

.PHONY : code/Graphics/ScanLine.o

# target to build an object file
code/Graphics/ScanLine.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/ScanLine.cpp.o
.PHONY : code/Graphics/ScanLine.cpp.o

code/Graphics/ScanLine.i: code/Graphics/ScanLine.cpp.i

.PHONY : code/Graphics/ScanLine.i

# target to preprocess a source file
code/Graphics/ScanLine.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/ScanLine.cpp.i
.PHONY : code/Graphics/ScanLine.cpp.i

code/Graphics/ScanLine.s: code/Graphics/ScanLine.cpp.s

.PHONY : code/Graphics/ScanLine.s

# target to generate assembly for a file
code/Graphics/ScanLine.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/ScanLine.cpp.s
.PHONY : code/Graphics/ScanLine.cpp.s

code/Graphics/TextureCoords.o: code/Graphics/TextureCoords.cpp.o

.PHONY : code/Graphics/TextureCoords.o

# target to build an object file
code/Graphics/TextureCoords.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/TextureCoords.cpp.o
.PHONY : code/Graphics/TextureCoords.cpp.o

code/Graphics/TextureCoords.i: code/Graphics/TextureCoords.cpp.i

.PHONY : code/Graphics/TextureCoords.i

# target to preprocess a source file
code/Graphics/TextureCoords.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/TextureCoords.cpp.i
.PHONY : code/Graphics/TextureCoords.cpp.i

code/Graphics/TextureCoords.s: code/Graphics/TextureCoords.cpp.s

.PHONY : code/Graphics/TextureCoords.s

# target to generate assembly for a file
code/Graphics/TextureCoords.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/TextureCoords.cpp.s
.PHONY : code/Graphics/TextureCoords.cpp.s

code/Graphics/TextureManager.o: code/Graphics/TextureManager.cpp.o

.PHONY : code/Graphics/TextureManager.o

# target to build an object file
code/Graphics/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/TextureManager.cpp.o
.PHONY : code/Graphics/TextureManager.cpp.o

code/Graphics/TextureManager.i: code/Graphics/TextureManager.cpp.i

.PHONY : code/Graphics/TextureManager.i

# target to preprocess a source file
code/Graphics/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/TextureManager.cpp.i
.PHONY : code/Graphics/TextureManager.cpp.i

code/Graphics/TextureManager.s: code/Graphics/TextureManager.cpp.s

.PHONY : code/Graphics/TextureManager.s

# target to generate assembly for a file
code/Graphics/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Graphics/TextureManager.cpp.s
.PHONY : code/Graphics/TextureManager.cpp.s

code/Input.o: code/Input.cpp.o

.PHONY : code/Input.o

# target to build an object file
code/Input.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Input.cpp.o
.PHONY : code/Input.cpp.o

code/Input.i: code/Input.cpp.i

.PHONY : code/Input.i

# target to preprocess a source file
code/Input.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Input.cpp.i
.PHONY : code/Input.cpp.i

code/Input.s: code/Input.cpp.s

.PHONY : code/Input.s

# target to generate assembly for a file
code/Input.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Input.cpp.s
.PHONY : code/Input.cpp.s

code/Maths/Math.o: code/Maths/Math.cpp.o

.PHONY : code/Maths/Math.o

# target to build an object file
code/Maths/Math.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Maths/Math.cpp.o
.PHONY : code/Maths/Math.cpp.o

code/Maths/Math.i: code/Maths/Math.cpp.i

.PHONY : code/Maths/Math.i

# target to preprocess a source file
code/Maths/Math.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Maths/Math.cpp.i
.PHONY : code/Maths/Math.cpp.i

code/Maths/Math.s: code/Maths/Math.cpp.s

.PHONY : code/Maths/Math.s

# target to generate assembly for a file
code/Maths/Math.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Maths/Math.cpp.s
.PHONY : code/Maths/Math.cpp.s

code/Maths/Vector2f.o: code/Maths/Vector2f.cpp.o

.PHONY : code/Maths/Vector2f.o

# target to build an object file
code/Maths/Vector2f.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Maths/Vector2f.cpp.o
.PHONY : code/Maths/Vector2f.cpp.o

code/Maths/Vector2f.i: code/Maths/Vector2f.cpp.i

.PHONY : code/Maths/Vector2f.i

# target to preprocess a source file
code/Maths/Vector2f.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Maths/Vector2f.cpp.i
.PHONY : code/Maths/Vector2f.cpp.i

code/Maths/Vector2f.s: code/Maths/Vector2f.cpp.s

.PHONY : code/Maths/Vector2f.s

# target to generate assembly for a file
code/Maths/Vector2f.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/Maths/Vector2f.cpp.s
.PHONY : code/Maths/Vector2f.cpp.s

code/States/EditState.o: code/States/EditState.cpp.o

.PHONY : code/States/EditState.o

# target to build an object file
code/States/EditState.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/States/EditState.cpp.o
.PHONY : code/States/EditState.cpp.o

code/States/EditState.i: code/States/EditState.cpp.i

.PHONY : code/States/EditState.i

# target to preprocess a source file
code/States/EditState.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/States/EditState.cpp.i
.PHONY : code/States/EditState.cpp.i

code/States/EditState.s: code/States/EditState.cpp.s

.PHONY : code/States/EditState.s

# target to generate assembly for a file
code/States/EditState.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/States/EditState.cpp.s
.PHONY : code/States/EditState.cpp.s

code/States/PlayState.o: code/States/PlayState.cpp.o

.PHONY : code/States/PlayState.o

# target to build an object file
code/States/PlayState.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/States/PlayState.cpp.o
.PHONY : code/States/PlayState.cpp.o

code/States/PlayState.i: code/States/PlayState.cpp.i

.PHONY : code/States/PlayState.i

# target to preprocess a source file
code/States/PlayState.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/States/PlayState.cpp.i
.PHONY : code/States/PlayState.cpp.i

code/States/PlayState.s: code/States/PlayState.cpp.s

.PHONY : code/States/PlayState.s

# target to generate assembly for a file
code/States/PlayState.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/States/PlayState.cpp.s
.PHONY : code/States/PlayState.cpp.s

code/World/BspTree.o: code/World/BspTree.cpp.o

.PHONY : code/World/BspTree.o

# target to build an object file
code/World/BspTree.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/BspTree.cpp.o
.PHONY : code/World/BspTree.cpp.o

code/World/BspTree.i: code/World/BspTree.cpp.i

.PHONY : code/World/BspTree.i

# target to preprocess a source file
code/World/BspTree.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/BspTree.cpp.i
.PHONY : code/World/BspTree.cpp.i

code/World/BspTree.s: code/World/BspTree.cpp.s

.PHONY : code/World/BspTree.s

# target to generate assembly for a file
code/World/BspTree.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/BspTree.cpp.s
.PHONY : code/World/BspTree.cpp.s

code/World/BspWall.o: code/World/BspWall.cpp.o

.PHONY : code/World/BspWall.o

# target to build an object file
code/World/BspWall.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/BspWall.cpp.o
.PHONY : code/World/BspWall.cpp.o

code/World/BspWall.i: code/World/BspWall.cpp.i

.PHONY : code/World/BspWall.i

# target to preprocess a source file
code/World/BspWall.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/BspWall.cpp.i
.PHONY : code/World/BspWall.cpp.i

code/World/BspWall.s: code/World/BspWall.cpp.s

.PHONY : code/World/BspWall.s

# target to generate assembly for a file
code/World/BspWall.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/BspWall.cpp.s
.PHONY : code/World/BspWall.cpp.s

code/World/Sector.o: code/World/Sector.cpp.o

.PHONY : code/World/Sector.o

# target to build an object file
code/World/Sector.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/Sector.cpp.o
.PHONY : code/World/Sector.cpp.o

code/World/Sector.i: code/World/Sector.cpp.i

.PHONY : code/World/Sector.i

# target to preprocess a source file
code/World/Sector.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/Sector.cpp.i
.PHONY : code/World/Sector.cpp.i

code/World/Sector.s: code/World/Sector.cpp.s

.PHONY : code/World/Sector.s

# target to generate assembly for a file
code/World/Sector.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/Sector.cpp.s
.PHONY : code/World/Sector.cpp.s

code/World/SectorWall.o: code/World/SectorWall.cpp.o

.PHONY : code/World/SectorWall.o

# target to build an object file
code/World/SectorWall.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/SectorWall.cpp.o
.PHONY : code/World/SectorWall.cpp.o

code/World/SectorWall.i: code/World/SectorWall.cpp.i

.PHONY : code/World/SectorWall.i

# target to preprocess a source file
code/World/SectorWall.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/SectorWall.cpp.i
.PHONY : code/World/SectorWall.cpp.i

code/World/SectorWall.s: code/World/SectorWall.cpp.s

.PHONY : code/World/SectorWall.s

# target to generate assembly for a file
code/World/SectorWall.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/SectorWall.cpp.s
.PHONY : code/World/SectorWall.cpp.s

code/World/Wall.o: code/World/Wall.cpp.o

.PHONY : code/World/Wall.o

# target to build an object file
code/World/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/Wall.cpp.o
.PHONY : code/World/Wall.cpp.o

code/World/Wall.i: code/World/Wall.cpp.i

.PHONY : code/World/Wall.i

# target to preprocess a source file
code/World/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/Wall.cpp.i
.PHONY : code/World/Wall.cpp.i

code/World/Wall.s: code/World/Wall.cpp.s

.PHONY : code/World/Wall.s

# target to generate assembly for a file
code/World/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/World/Wall.cpp.s
.PHONY : code/World/Wall.cpp.s

code/main.o: code/main.cpp.o

.PHONY : code/main.o

# target to build an object file
code/main.cpp.o:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/main.cpp.o
.PHONY : code/main.cpp.o

code/main.i: code/main.cpp.i

.PHONY : code/main.i

# target to preprocess a source file
code/main.cpp.i:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/main.cpp.i
.PHONY : code/main.cpp.i

code/main.s: code/main.cpp.s

.PHONY : code/main.s

# target to generate assembly for a file
code/main.cpp.s:
	$(MAKE) -f CMakeFiles/foom.dir/build.make CMakeFiles/foom.dir/code/main.cpp.s
.PHONY : code/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... foom"
	@echo "... edit_cache"
	@echo "... code/Application.o"
	@echo "... code/Application.i"
	@echo "... code/Application.s"
	@echo "... code/Display.o"
	@echo "... code/Display.i"
	@echo "... code/Display.s"
	@echo "... code/Entities/Camera.o"
	@echo "... code/Entities/Camera.i"
	@echo "... code/Entities/Camera.s"
	@echo "... code/Graphics/FrameBuffers/Bitmap.o"
	@echo "... code/Graphics/FrameBuffers/Bitmap.i"
	@echo "... code/Graphics/FrameBuffers/Bitmap.s"
	@echo "... code/Graphics/FrameBuffers/GameRenderer.o"
	@echo "... code/Graphics/FrameBuffers/GameRenderer.i"
	@echo "... code/Graphics/FrameBuffers/GameRenderer.s"
	@echo "... code/Graphics/FrameBuffers/RenderContext.o"
	@echo "... code/Graphics/FrameBuffers/RenderContext.i"
	@echo "... code/Graphics/FrameBuffers/RenderContext.s"
	@echo "... code/Graphics/ScanLine.o"
	@echo "... code/Graphics/ScanLine.i"
	@echo "... code/Graphics/ScanLine.s"
	@echo "... code/Graphics/TextureCoords.o"
	@echo "... code/Graphics/TextureCoords.i"
	@echo "... code/Graphics/TextureCoords.s"
	@echo "... code/Graphics/TextureManager.o"
	@echo "... code/Graphics/TextureManager.i"
	@echo "... code/Graphics/TextureManager.s"
	@echo "... code/Input.o"
	@echo "... code/Input.i"
	@echo "... code/Input.s"
	@echo "... code/Maths/Math.o"
	@echo "... code/Maths/Math.i"
	@echo "... code/Maths/Math.s"
	@echo "... code/Maths/Vector2f.o"
	@echo "... code/Maths/Vector2f.i"
	@echo "... code/Maths/Vector2f.s"
	@echo "... code/States/EditState.o"
	@echo "... code/States/EditState.i"
	@echo "... code/States/EditState.s"
	@echo "... code/States/PlayState.o"
	@echo "... code/States/PlayState.i"
	@echo "... code/States/PlayState.s"
	@echo "... code/World/BspTree.o"
	@echo "... code/World/BspTree.i"
	@echo "... code/World/BspTree.s"
	@echo "... code/World/BspWall.o"
	@echo "... code/World/BspWall.i"
	@echo "... code/World/BspWall.s"
	@echo "... code/World/Sector.o"
	@echo "... code/World/Sector.i"
	@echo "... code/World/Sector.s"
	@echo "... code/World/SectorWall.o"
	@echo "... code/World/SectorWall.i"
	@echo "... code/World/SectorWall.s"
	@echo "... code/World/Wall.o"
	@echo "... code/World/Wall.i"
	@echo "... code/World/Wall.s"
	@echo "... code/main.o"
	@echo "... code/main.i"
	@echo "... code/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

